### PR TITLE
Fix import when the image is not in the user's default group

### LINKED ISSUE #22: Importing ROIs into OMERO fails when image is not in user's default group
```ome-omero-roitool import``` with an image ID not in the default group throws ```omero.SecurityViolation```.  I think there just needs to be an extra command line option to specify the group during login.

### PR DESCRIPTION
**Pull request by melissalinkert**
This allows importing/exporting with an image that is not in the user's default group.

Fixes #22.

### CODE REVIEW

File: src/main/java/com/glencoesoftware/roitool/ROIMetadataStoreClient.java [hunk 1]
```diff
@@ -123,13 +127,36 @@ private Roi getRoi(int roiIndex)
...
+
+        Map<String, String> queryCtx = new HashMap<String, String>();
+        queryCtx.put("omero.group", "-1");
+        IQueryPrx q = (IQueryPrx) sf.getQueryService().ice_context(queryCtx);
+        String query = "select i from Image i where i.id = :id";
+
+        ParametersI p = new ParametersI();
+        p.add("id", rlong(imageId));
+
+        List<IObject> results = q.findAllByQuery(query, p);
```
Comment (chris-allan) [inline src/main/java/com/glencoesoftware/roitool/ROIMetadataStoreClient.java:142]: `findByQuery()` will return one object. `get("Image", image_id)` could also be used.
